/**
 * 行程清单（单一数据源）：ingest-photos.mjs（照片入库）与 gen-scenes.mjs（子景点清单）共用。
 * id 同时是 photos/ 与路由目录名；坐标人工标注（微信传输会剥离照片 EXIF GPS）。
 * 增加一次旅行 = 这里加一条配置 + node scripts/ingest-photos.mjs --only=<id>。
 */
export const TRIPS = [
  {
    id: 'sanxindui',
    src: '三星堆26.4.15',
    title: '三星堆博物馆',
    date: '2026-04-15',
    place: { name: '三星堆博物馆', country: '中国', province: '四川', lng: 104.393, lat: 30.99 },
    tags: ['博物馆', '古蜀文明', '青铜器'],
    description: '沉睡三千年，一醒惊天下。青铜大立人、纵目面具和那棵神树，古蜀人的想象力隔着三千年扑面而来。',
  },
  {
    id: 'shanghai',
    src: '上海 25.12.14',
    title: '上海',
    date: '2025-12-14',
    place: { name: '上海', country: '中国', province: '上海', lng: 121.4737, lat: 31.2304 },
    tags: ['都市', '外滩'],
    description: '十二月的上海，梧桐叶落尽，外滩的风比想象中硬。这座城市最迷人的时刻是华灯初上的那半小时。',
  },
  {
    id: 'yunnan',
    src: '云南 25.1.19-28',
    title: '云南环线：昆明 · 大理 · 丽江 · 西双版纳',
    date: '2025-01-19',
    place: { name: '大理古城', country: '中国', province: '云南', lng: 100.272, lat: 25.606 },
    tags: ['环线', '古城', '洱海', '雪山'],
    description: '十天环形路线：昆明的老街与翠湖、大理的古城与洱海、丽江的束河古镇，一路向南直到西双版纳的雨林。一月避寒的完美答案。',
  },
  {
    id: 'shandong',
    src: '山东 25.12.15-20',
    title: '山东半岛：威海 · 烟台 · 青岛',
    date: '2025-12-15',
    place: { name: '青岛', country: '中国', province: '山东', lng: 120.3826, lat: 36.0671 },
    tags: ['海岸线', '冬季大海', '无人机'],
    description: '冬天的山东半岛几乎没有人：威海的雪后海岸、烟台的老码头、青岛的红瓦绿树。带了无人机，把海岸线从空中又看了一遍。',
  },
  {
    id: 'shanxi-huashan',
    src: '山西 26.7.27-8.4',
    title: '晋陕之行：华山 · 太原 · 大同',
    date: '2026-07-27',
    place: { name: '大同', country: '中国', province: '山西', lng: 113.3001, lat: 40.0768 },
    tags: ['华山', '晋祠', '云冈石窟', '古建'],
    description: '从华山的长空栈道开始，经太原晋祠一路向北到大同云冈——一条从险峰到石窟的纵深线，也是半部中国古建史。',
  },
  {
    id: 'luoyang',
    src: '洛阳',
    title: '洛阳',
    date: '2024-08-24',
    place: { name: '洛阳', country: '中国', province: '河南', lng: 112.454, lat: 34.6197 },
    tags: ['古都', '十三朝'],
    description: '十三个王朝在此建都。应天门的夜景、白马寺的钟声，洛阳把「厚重」两个字写在了每一块城砖上。',
  },
  {
    id: 'guizhou',
    src: '贵州 26.8.25-29',
    title: '贵州：黔灵山 · 黄果树 · 荔波小七孔',
    date: '2026-08-25',
    place: { name: '黄果树瀑布', country: '中国', province: '贵州', lng: 105.673, lat: 25.995 },
    tags: ['瀑布', '喀斯特', '避暑'],
    description: '八月入黔避暑：黔灵山的猴、黄果树的水雾、小七孔的绿。喀斯特地貌把这条线路串成了一部地质教科书。',
  },
  {
    id: 'dujiangyan',
    src: '都江堰25.10.1',
    title: '都江堰',
    date: '2025-10-01',
    place: { name: '都江堰', country: '中国', province: '四川', lng: 103.6183, lat: 31.005 },
    tags: ['水利', '古堰', '国庆'],
    description: '两千两百多年前李冰父子修的堰，至今还在灌溉成都平原。站在鱼嘴分水堤上看岷江被一分为二，才理解什么叫「道法自然」。',
  },
  {
    id: 'chongqing',
    src: '重庆25.8.12-15',
    title: '重庆 · 三峡：万州 · 白帝城 · 三峡大坝',
    date: '2025-08-12',
    place: { name: '重庆', country: '中国', province: '重庆', lng: 106.5505, lat: 29.563 },
    tags: ['山城', '长江', '三峡'],
    description: '从山城的立体交通到长江游轮：万州天生城、白帝城夔门、三峡大坝。四天时间，把李白「朝辞白帝彩云间」的那段江走了一遍。',
  },
  {
    id: 'jinjiang',
    src: '锦江',
    title: '成都 · 锦江',
    date: '2026-06-19',
    place: { name: '锦江', country: '中国', province: '四川', lng: 104.081, lat: 30.652 },
    tags: ['江畔', '夜游'],
    description: '不出远门的周末：沿锦江慢慢走，看这座城市在水面里的倒影。旅行不一定要远行。',
  },
  {
    id: 'qingcheng',
    src: '青城后山',
    title: '青城后山',
    date: '2025-04-11',
    place: { name: '青城后山', country: '中国', province: '四川', lng: 103.545, lat: 30.925 },
    tags: ['青城山', '徒步', '幽'],
    description: '「青城天下幽」说的其实是后山：飞泉、栈道、一路的水声。前山看道观，后山听山。',
  },
  {
    id: 'longquanshan',
    src: '龙泉山',
    title: '龙泉山',
    date: '2024-01-25',
    place: { name: '龙泉山', country: '中国', province: '四川', lng: 104.274, lat: 30.567 },
    tags: ['日出', '城市远眺'],
    description: '成都人的后院：上龙泉山等一场日出，看整座城市在脚下慢慢醒来。',
  },
];
